### ISSUE TITLE
Referenced XML-Schema unknown for VolumeIndex

### ISSUE THREAD

**Issue by GoogleCodeExporter** [tmeiczin/opendcp#251]
```
*Please fill in all defect information below.*

Product Version:0.29.0 64-bit
GUI or CLI: GUI
Operating system: Windows 7

What steps will reproduce the problem?
1. Build Interop DCP package using OpenDCP
2. Load Interop DCP into EasyDCP Player Demo for package validation
3. Automatic XML validation against corresponding schema

What is the expected output?

DCP validation process in EasyDCP Player with no warnings or errors


What is actual output?

EasyDCP Player reports error while performing the operation "Validate XML files 
against their corresponding XML Schemas": 

code 60003 from pet svi 23 14:11:47 2014:
Referenced XML-Schema unknown
Element '{http://www.digicine.com/PROTO-ASDCP-AM-20040311#}VolumeIndex': No 
matching global declaration available for the validation root.

Please provide any additional information below.

Output from OpenDCP 0.27.1 or later seems to be affected, it is not known which 
earlier version may not exhibit the issue...problem DCP builds not yet tested 
for compliance or "pass" on an actual digital cinema system...
```

Original issue reported on code.google.com by `mytb...@gmail.com` on 23 May 2014 at 2:15

**Comment by rlschroeder** [comment]
Sorry to reopen this years later... I got in touch with EasyDCP regarding the issue. Here was their response.... 

> 
> - the namespace you're using does not define anything related to the Volume Index
> - while the VL namespace/schema is not really defined, it is used in basically all commercial mastering solutions out there
> 
> The situation has been discussed even at ISDCF in the past and there is no good solution to it.
> 
> We could probably degrade this error to a warning. But then, OpenDCP could also just use the namespace that everybody else is using, since there is no specification that says that http://www.digicine.com/PROTO-ASDCP-AM-20040311# is to be used in the volume index.

Thoughts on this?

**Comment by AnjaMahler** [comment]
Thanks this is very useful! I just had exactly the same issue with a DCP created with Wraptor.  I am validating DCPs with EasyDCP Player 3.4.11 for long term preservation and would usually reject on error but I am uncertain how this can be fixed if the content producer uses either of these creators. 

<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<VolumeIndex xmlns="http://www.digicine.com/PROTO-ASDCP-AM-20040311#">
  <Index>1</Index>
</VolumeIndex>

**Comment by rlschroeder** [comment]
I've contacted EasyDCP about the issue - this is what I sent them.

> I had verified my DCP with TIME_QC and dcp_inspect - both greenlit the DCP. I sent the DCP out and had an EasyDCP+ report returned to me with an error. Attached is that report.
> 
> The problem reported is that the schema being referenced isn't correct - it doesn't say anything about whether the schema is, in fact, correct or not, which is what would affect whether the DCP is playable or not.
> Also, the schema referenced, that easyDCP wants to see - http://www.digicine.com/PROTO-ASDCP-VL-20040311# - doesn't exist.
> However, the one I have in there - http://www.digicine.com/PROTO-ASDCP-AM-20040311# - certainly does.
> The first URL will give you an error, the second takes you to what I'd expect - a reference for an Asset Map of an Interop DCP.
> 
> According to this, it might be a bug in EasyDCP. https://github.com/tmeiczin/opendcp/issues/251 - thoughts on this?

To that, they responded with:

> - the namespace you're using does not define anything related to the Volume Index
> - while the VL namespace/schema is not really defined, it is used in basically all commercial mastering solutions out there
> 
> The situation has been discussed even at ISDCF in the past and there is no good solution to it.
> 
> We could probably degrade this error to a warning. But then, OpenDCP could also just use the namespace that everybody else is using, since there is no specification that says that http://www.digicine.com/PROTO-ASDCP-AM-20040311# is to be used in the volume index.

I then asked if I could just change the string in VOLINDEX to the one requested by EasyDCP, as it's just a small text file that one can easily edit.

> Gotcha. Well, I'll check with OpenDCP about it as well. It would probably be best to change that kind of thing to a Warning, yes.
> Will I have any issues if I simply change the string in VOLINDEX to http://www.digicine.com/PROTO-ASDCP-VL-20040311# in a text editor?

To which they confirmed that, yes, you can do that. 

> The VOLINDEX file is not hashed or listed in the PackingList, so yes, you can change it in a text editor. But don't touch PKL/CPL!

So there you go - if you want to avoid the EasyDCP error, simply change the "AM" to a "VL" in the VOLINDEX file with a text editor and you should be good to go.

**Comment by AnjaMahler** [comment]
Thanks so much! This is very interesting and insightful! I will test and feedback to content producers.

**Comment by tmeiczin** [comment]
There certainly have been many conversations in regard to this. The MXF Interop was never a finalized specification and was superseded by the SMPTE standard which has the schema clearly defined. It has been the recommendation to use SMPTE packaging for many years now as MXF Interop is deprecated.

**Comment by rlschroeder** [comment]
That's a good call. I've had some post houses still recommend Interop - old servers perhaps? Not sure why. SMPTE packaging sounds like a good route though.
