### ISSUE TITLE
Opendcp_mxf does not properly create 23.98 mxf's

### ISSUE THREAD

**Issue by bquandt** [tmeiczin/opendcp#269]
asdcp-test supports 23.98, but when you set the rate to 23 (23.98) or some combination you don't get what you'd expect.

Now don't know what 23/1 means in the DCI world, maybe that translates to 24000/1001, but if it does it sure violates what my grade school teacher told me about fractions?

A simple test of using asdcp-test to make my DCP with a framerate set to "23" per their notes, it does get set to what I'd expect in the MXF header, ie 24000/1001.

**Comment by tmeiczin** [comment]
23.98 is not supported by OpenDCP. Only integer frame rates are supported.
