### ISSUE TITLE
GIT_REPOSITORY for openjpeg is wrong

### ISSUE THREAD

**Issue by szukw000** [tmeiczin/opendcp#270]
The git repository path is wrong:

--- opendcp-master-2013-04-10/contrib/CMakeLists.txt.orig   2015-04-11 13:11:58.814916000 +0000
+++ opendcp-master-2013-04-10/contrib/CMakeLists.txt    2015-04-11 13:14:23.322930219 +0000
@@ -199,7 +199,7 @@
     SET(INSTALL_PREFIX ${CMAKE_CURRENT_BINARY_DIR})
     EXTERNALPROJECT_ADD(
         09_OpenJPEG
-        GIT_REPOSITORY "https://github.com/OpenJPEG/openjpeg.git"
+        GIT_REPOSITORY "git://github.com/uclouvain/openjpeg.git"
         GIT_TAG "tags/version.2.1"
         CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX}
         CONFIGURE_COMMAND ${CMAKE} ../09_OpenJPEG -DBUILD_CODEC=OFF -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX} -DBUILD_SHARED_LIBS=OFF -DOPENJPEG_INSTALL_INCLUDE_DIR=${INSTALL_PREFIX}/include -DCMAKE_BUILD_TYPE=RELEASE

winfried

**Comment by tmeiczin** [comment]
Updated. Thanks.
