### ISSUE TITLE
Wrong website address in the description

### ISSUE THREAD

**Issue by retokromer** [tmeiczin/opendcp#291]
Replace `Created digital cinemas packages (DCP) http://wwww.opendcp.org/` (four `w`) by `Created digital cinemas packages (DCP) http://www.opendcp.org/`.

**Comment by retokromer** [comment]
ping

**Comment by retokromer** [comment]
It’s actually the same as https://github.com/tmeiczin/opendcp/issues/283 therefore I close this one. Is this project dead?

**Comment by tmeiczin** [comment]
Thanks. The project isn't "dead", but due to time constraints, I've been unable to get some updates released.
