### ISSUE TITLE
Title generator - Whats should the finished DCP look like in finder?

### ISSUE THREAD

**Issue by mrlowndes** [tmeiczin/opendcp#311]
Hello. Noob here

I went through the steps to generate a title but when I finally create my DCP, I don't see that title anywhere on the file generated. Is there a definitive guide anywhere that lays out the steps for creating a DCP? Thanks

**Comment by tmeiczin** [comment]
The title would not be on the file itself, its metadata. People have done some several excellent tutorials over the years, which you can find searching YouTube or Google.
