### ISSUE TITLE
32 bit version Crashes

### ISSUE THREAD

**Issue by Jerronemo45** [tmeiczin/opendcp#312]
Hey there.
Is there a chance to have a 64 bit version back online? The 32 bit crashes every time... Am not even getting an error but guessing there's something to do with the ram

Much appreciated
Thank you.

**Comment by tmeiczin** [comment]
You can download it here https://github.com/tmeiczin/opendcp/releases/download/v0.30.0/opendcp-0.30.0-windows.x86_64.exe

**Comment by Jerronemo45** [comment]
Thank you so much..

Alexandros Yennaris

2d/3d Animator & Digital VFX

ayennaris.com
<https://mailtrack.io/trace/link/fbad81fb8ec73e4c54f6e47b8be4f376df7116f0?url=http%3A%2F%2Fwww.ayennaris.com%2F&userId=2024864&signature=bcd428098e265817>
| +35799531845

<https://mailtrack.io/trace/link/197e3a548f7d49da9d60079c3de0d479d1f4a22f?url=https%3A%2F%2Fvimeo.com%2Fyennaris&userId=2024864&signature=4ba051972e15bae4>
<https://mailtrack.io/trace/link/4ce58df2bac8038f2e7c0229dbefe9224119da33?url=https%3A%2F%2Fwww.linkedin.com%2Fin%2Fayennaris%2F&userId=2024864&signature=4a5947c8159a54b2>
<https://mailtrack.io/trace/link/3e43a82ade8864b1dcfc6fcad7061007d5fd8bc9?url=https%3A%2F%2Fwww.instagram.com%2Fjerronemo%2F&userId=2024864&signature=4763c678ae826695>
