### ISSUE TITLE
"Improved XYZ color conversion" and color workflow

### ISSUE THREAD

**Issue by GoogleCodeExporter** [tmeiczin/opendcp#36]
```
What steps will reproduce the problem?
1. in the release notes, for 0.16 version you have written :
2. "Improved XYZ color conversion"
3.

What is the expected output? What do you see instead?
I didn't test yet but I just wanted to know what kind of "improvements" you 
made in the XYZ color correction... I made a DCP from TIFF files generated in 
Rec.709 by After Effects CS5 these last days and I've seen a difference between 
the J2C files created by opendcp_j2k and other J2C files made from TIFF files 
in "DCDM XYZ Adobe 5900K gamma 2.6" and converted by opendcp_j2k with the "-x" 
option (to prevent from a double color space correction).

Is that this mismatch I can expect to be corrected with the 0.16 version of 
opendcp ?

What version of the product are you using? On what operating system?
0.16 on Mac OS X

Please provide any additional information below.
I will go in a digital cinema theatre soon... and i will test 5 different 
workflows...

A : After Effects 32-bit linear Universal Printing Density color space -> TIFF 
16-bit Rec.709 RGB -> opendcp_j2k -> J2C XYZ
B : After Effects 32-bit linear Universal Printing Density color space -> TIFF 
16-bit DCDM XYZ -> opendcp_j2k -x -> J2C XYZ
C : After Effects 16-bit no color space -> TIFF 16-bit RGB -> opendcp_j2k -> 
J2C XYZ
D : After Effects 16-bit no color space + color space utilitie "working space 
to DCDM XYZ" -> TIFF 16-bit DCDM XYZ -> opendcp_j2k -x -> J2C XYZ
E : After Effects 32-bit linear Universal Printing Density color space + gamma 
1.22:1 correction -> TIFF 16-bit Rec.709 RGB -> opendcp_j2k -> J2C XYZ

If you have any suggestion tell me... and I will tell wich way is the best to 
maintain correct colors from a calibrated 10-bit HD monitor to a Digital Cinema 
projector...

Thanks (from France ! ^^) for all your amazing work... :)
```

Original issue reported on code.google.com by `fredz...@gmail.com` on 29 Jan 2011 at 8:43

**Comment by MCL** [comment]
Hello, 

Any further progress on the gamma question ?
I've just done my first DCP: 
From Rec709 to DCDM XYZ  gamma 2.6 in After Effect exporting directly in .j2C using the J2K pluggin, 
then using the MXF and DCP part of OpenDCP.

It's working and the colors are fine, however in the theater the blacks are a bit grey and they let appear some compression artifacts. 

Any piece of advice ?

Thank you

**Comment by tmeiczin** [comment]
OpenDCP does not alter the gamma during the MXF and DCP operations, so the issue you are seeing is with AE or the plugin.

**Comment by MCL** [comment]
That's what I thought so it has to come from the color conversion in After Effect. 
If the conversion from Rec709 to DCDM XYZ is making the image a bit to light in theater. Is there a specific setting I should pay attention to in After Effect ?

**Comment by tmeiczin** [comment]
Sorry, no idea. I'd suggest trying the Adobe forums.

**Comment by MCL** [comment]
No worries.

I think it might come from the fact that the color correction was done on a monitor and not in projection.
 
A friend told me it gives generally blacks that are +10mV higher than then should be and I should convert it in the first place, to make my SMPTE blacks become Full or CGR blacks.

I'll try to get more infos on that... :)
